import type { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    default: "BD tracker",
    template: `%s | BD tracker`,
  },
  description: "Generated by create next app",
};

export { App as default } from "@/app/App";
