import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "BD tracker",
  description: "Generated by create next app",
};

export { HomePage as default } from "@/pages/HomePage";
